apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-17T08:24:55Z"
  labels:
    run: wordpress
  name: wordpress
  namespace: default
  resourceVersion: "44364"
  uid: 54b465ac-1b97-44bb-b045-0158c15094c7
spec:
  clusterIP: 10.99.184.248
  clusterIPs:
  - 10.99.184.248
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: wordpress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
